throw ValueError // 待 catch 重现后添加到测试集